routes/web.php
<?php

Route::redirect('/', '/login');
Route::get('/home', function () {
    if (session('status')) {
        return redirect()->route('admin.home')->with('status', session('status'));
    }

    return redirect()->route('admin.home');
});

Auth::routes(['register' => false]);

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    // Permissions
    Route::delete('permissions/destroy', 'PermissionsController@massDestroy')->name('permissions.massDestroy');
    Route::resource('permissions', 'PermissionsController');

    // Roles
    Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');
    Route::resource('roles', 'RolesController');

    // Users
    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');
    Route::post('users/media', 'UsersController@storeMedia')->name('users.storeMedia');
    Route::post('users/ckmedia', 'UsersController@storeCKEditorImages')->name('users.storeCKEditorImages');
    Route::resource('users', 'UsersController');

    // User Search Options
    Route::delete('user-search-options/destroy', 'UserSearchOptionController@massDestroy')->name('user-search-options.massDestroy');
    Route::resource('user-search-options', 'UserSearchOptionController');

    // Bank Accounts
    Route::delete('bank-accounts/destroy', 'BankAccountController@massDestroy')->name('bank-accounts.massDestroy');
    Route::resource('bank-accounts', 'BankAccountController');

    // Payouts
    Route::delete('payouts/destroy', 'PayoutController@massDestroy')->name('payouts.massDestroy');
    Route::resource('payouts', 'PayoutController');

    // Credit Cards
    Route::delete('credit-cards/destroy', 'CreditCardController@massDestroy')->name('credit-cards.massDestroy');
    Route::resource('credit-cards', 'CreditCardController');

    // Alerts
    Route::delete('alerts/destroy', 'AlertController@massDestroy')->name('alerts.massDestroy');
    Route::resource('alerts', 'AlertController');

    // Cars
    Route::delete('cars/destroy', 'CarController@massDestroy')->name('cars.massDestroy');
    Route::resource('cars', 'CarController');
});
Route::group(['prefix' => 'profile', 'as' => 'profile.', 'namespace' => 'Auth', 'middleware' => ['auth']], function () {
// Change password
    if (file_exists(app_path('Http/Controllers/Auth/ChangePasswordController.php'))) {
        Route::get('password', 'ChangePasswordController@edit')->name('password.edit');
        Route::post('password', 'ChangePasswordController@update')->name('password.update');
        Route::post('profile', 'ChangePasswordController@updateProfile')->name('password.updateProfile');
        Route::post('profile/destroy', 'ChangePasswordController@destroy')->name('password.destroyProfile');
    }
});

app/Models/CreditCard.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use \DateTimeInterface;

class CreditCard extends Model
{
    use SoftDeletes, HasFactory;

    public $table = 'credit_cards';

    const IS_DEFAULT_RADIO = [
        true  => 'True',
        false => 'False',
    ];

    protected $dates = [
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    protected $fillable = [
        'user_id',
        'name',
        'token',
        'last_digits',
        'is_default',
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    protected $casts = [
        'is_default' => 'boolean',
    ];

    protected function serializeDate(DateTimeInterface $date)
    {
        return $date->format('Y-m-d H:i:s');
    }

    public function user()
    {
        return $this->belongsTo(User::class, 'user_id');
    }
}

app/Http/Controllers/Admin/CreditCardController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\MassDestroyCreditCardRequest;
use App\Http\Requests\StoreCreditCardRequest;
use App\Http\Requests\UpdateCreditCardRequest;
use App\Models\CreditCard;
use App\Models\User;
use Gate;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;
use Yajra\DataTables\Facades\DataTables;

class CreditCardController extends Controller
{
    public function index(Request $request)
    {
        abort_if(Gate::denies('credit_card_access'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        if ($request->ajax()) {
            $query = CreditCard::with(['user'])->select(sprintf('%s.*', (new CreditCard)->table));
            $table = Datatables::of($query);

            $table->addColumn('placeholder', '&nbsp;');
            $table->addColumn('actions', '&nbsp;');

            $table->editColumn('actions', function ($row) {
                $viewGate      = 'credit_card_show';
                $editGate      = 'credit_card_edit';
                $deleteGate    = 'credit_card_delete';
                $crudRoutePart = 'credit-cards';

                return view('partials.datatablesActions', compact(
                    'viewGate',
                    'editGate',
                    'deleteGate',
                    'crudRoutePart',
                    'row'
                ));
            });

            $table->editColumn('id', function ($row) {
                return $row->id ? $row->id : "";
            });
            $table->addColumn('user_email', function ($row) {
                return $row->user ? $row->user->email : '';
            });

            $table->editColumn('name', function ($row) {
                return $row->name ? $row->name : "";
            });
            $table->editColumn('token', function ($row) {
                return $row->token ? $row->token : "";
            });
            $table->editColumn('last_digits', function ($row) {
                return $row->last_digits ? $row->last_digits : "";
            });
            $table->editColumn('is_default', function ($row) {
                return $row->is_default ? CreditCard::IS_DEFAULT_RADIO[$row->is_default] : '';
            });

            $table->rawColumns(['actions', 'placeholder', 'user']);

            return $table->make(true);
        }

        return view('admin.creditCards.index');
    }

    public function create()
    {
        abort_if(Gate::denies('credit_card_create'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $users = User::all()->pluck('email', 'id')->prepend(trans('global.pleaseSelect'), '');

        return view('admin.creditCards.create', compact('users'));
    }

    public function store(StoreCreditCardRequest $request)
    {
        $creditCard = CreditCard::create($request->all());

        return redirect()->route('admin.credit-cards.index');
    }

    public function edit(CreditCard $creditCard)
    {
        abort_if(Gate::denies('credit_card_edit'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $users = User::all()->pluck('email', 'id')->prepend(trans('global.pleaseSelect'), '');

        $creditCard->load('user');

        return view('admin.creditCards.edit', compact('users', 'creditCard'));
    }

    public function update(UpdateCreditCardRequest $request, CreditCard $creditCard)
    {
        $creditCard->update($request->all());

        return redirect()->route('admin.credit-cards.index');
    }

    public function show(CreditCard $creditCard)
    {
        abort_if(Gate::denies('credit_card_show'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $creditCard->load('user');

        return view('admin.creditCards.show', compact('creditCard'));
    }

    public function destroy(CreditCard $creditCard)
    {
        abort_if(Gate::denies('credit_card_delete'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $creditCard->delete();

        return back();
    }

    public function massDestroy(MassDestroyCreditCardRequest $request)
    {
        CreditCard::whereIn('id', request('ids'))->delete();

        return response(null, Response::HTTP_NO_CONTENT);
    }
}

resources/views/admin/creditCards/create.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.create') }} {{ trans('cruds.creditCard.title_singular') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("admin.credit-cards.store") }}" enctype="multipart/form-data">
            @csrf
            <div class="form-group">
                <label class="required" for="user_id">{{ trans('cruds.creditCard.fields.user') }}</label>
                <select class="form-control select2 {{ $errors->has('user') ? 'is-invalid' : '' }}" name="user_id" id="user_id" required>
                    @foreach($users as $id => $user)
                        <option value="{{ $id }}" {{ old('user_id') == $id ? 'selected' : '' }}>{{ $user }}</option>
                    @endforeach
                </select>
                @if($errors->has('user'))
                    <div class="invalid-feedback">
                        {{ $errors->first('user') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.creditCard.fields.user_helper') }}</span>
            </div>
            <div class="form-group">
                <label class="required" for="name">{{ trans('cruds.creditCard.fields.name') }}</label>
                <input class="form-control {{ $errors->has('name') ? 'is-invalid' : '' }}" type="text" name="name" id="name" value="{{ old('name', '') }}" required>
                @if($errors->has('name'))
                    <div class="invalid-feedback">
                        {{ $errors->first('name') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.creditCard.fields.name_helper') }}</span>
            </div>
            <div class="form-group">
                <label class="required" for="token">{{ trans('cruds.creditCard.fields.token') }}</label>
                <input class="form-control {{ $errors->has('token') ? 'is-invalid' : '' }}" type="text" name="token" id="token" value="{{ old('token', '') }}" required>
                @if($errors->has('token'))
                    <div class="invalid-feedback">
                        {{ $errors->first('token') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.creditCard.fields.token_helper') }}</span>
            </div>
            <div class="form-group">
                <label class="required" for="last_digits">{{ trans('cruds.creditCard.fields.last_digits') }}</label>
                <input class="form-control {{ $errors->has('last_digits') ? 'is-invalid' : '' }}" type="text" name="last_digits" id="last_digits" value="{{ old('last_digits', '') }}" required>
                @if($errors->has('last_digits'))
                    <div class="invalid-feedback">
                        {{ $errors->first('last_digits') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.creditCard.fields.last_digits_helper') }}</span>
            </div>
            <div class="form-group">
                <label class="required">{{ trans('cruds.creditCard.fields.is_default') }}</label>
                @foreach(App\Models\CreditCard::IS_DEFAULT_RADIO as $key => $label)
                    <div class="form-check {{ $errors->has('is_default') ? 'is-invalid' : '' }}">
                        <input class="form-check-input" type="radio" id="is_default_{{ $key }}" name="is_default" value="{{ $key }}" {{ old('is_default', '') === (string) $key ? 'checked' : '' }} required>
                        <label class="form-check-label" for="is_default_{{ $key }}">{{ $label }}</label>
                    </div>
                @endforeach
                @if($errors->has('is_default'))
                    <div class="invalid-feedback">
                        {{ $errors->first('is_default') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.creditCard.fields.is_default_helper') }}</span>
            </div>
            <div class="form-group">
                <button class="btn btn-danger" type="submit">
                    {{ trans('global.save') }}
                </button>
            </div>
        </form>
    </div>
</div>



@endsection

resources/views/admin/creditCards/edit.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.edit') }} {{ trans('cruds.creditCard.title_singular') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("admin.credit-cards.update", [$creditCard->id]) }}" enctype="multipart/form-data">
            @method('PUT')
            @csrf
            <div class="form-group">
                <label class="required" for="user_id">{{ trans('cruds.creditCard.fields.user') }}</label>
                <select class="form-control select2 {{ $errors->has('user') ? 'is-invalid' : '' }}" name="user_id" id="user_id" required>
                    @foreach($users as $id => $user)
                        <option value="{{ $id }}" {{ (old('user_id') ? old('user_id') : $creditCard->user->id ?? '') == $id ? 'selected' : '' }}>{{ $user }}</option>
                    @endforeach
                </select>
                @if($errors->has('user'))
                    <div class="invalid-feedback">
                        {{ $errors->first('user') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.creditCard.fields.user_helper') }}</span>
            </div>
            <div class="form-group">
                <label class="required" for="name">{{ trans('cruds.creditCard.fields.name') }}</label>
                <input class="form-control {{ $errors->has('name') ? 'is-invalid' : '' }}" type="text" name="name" id="name" value="{{ old('name', $creditCard->name) }}" required>
                @if($errors->has('name'))
                    <div class="invalid-feedback">
                        {{ $errors->first('name') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.creditCard.fields.name_helper') }}</span>
            </div>
            <div class="form-group">
                <label class="required" for="token">{{ trans('cruds.creditCard.fields.token') }}</label>
                <input class="form-control {{ $errors->has('token') ? 'is-invalid' : '' }}" type="text" name="token" id="token" value="{{ old('token', $creditCard->token) }}" required>
                @if($errors->has('token'))
                    <div class="invalid-feedback">
                        {{ $errors->first('token') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.creditCard.fields.token_helper') }}</span>
            </div>
            <div class="form-group">
                <label class="required" for="last_digits">{{ trans('cruds.creditCard.fields.last_digits') }}</label>
                <input class="form-control {{ $errors->has('last_digits') ? 'is-invalid' : '' }}" type="text" name="last_digits" id="last_digits" value="{{ old('last_digits', $creditCard->last_digits) }}" required>
                @if($errors->has('last_digits'))
                    <div class="invalid-feedback">
                        {{ $errors->first('last_digits') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.creditCard.fields.last_digits_helper') }}</span>
            </div>
            <div class="form-group">
                <label class="required">{{ trans('cruds.creditCard.fields.is_default') }}</label>
                @foreach(App\Models\CreditCard::IS_DEFAULT_RADIO as $key => $label)
                    <div class="form-check {{ $errors->has('is_default') ? 'is-invalid' : '' }}">
                        <input class="form-check-input" type="radio" id="is_default_{{ $key }}" name="is_default" value="{{ $key }}" {{ old('is_default', $creditCard->is_default) === (string) $key ? 'checked' : '' }} required>
                        <label class="form-check-label" for="is_default_{{ $key }}">{{ $label }}</label>
                    </div>
                @endforeach
                @if($errors->has('is_default'))
                    <div class="invalid-feedback">
                        {{ $errors->first('is_default') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.creditCard.fields.is_default_helper') }}</span>
            </div>
            <div class="form-group">
                <button class="btn btn-danger" type="submit">
                    {{ trans('global.save') }}
                </button>
            </div>
        </form>
    </div>
</div>



@endsection

resources/views/admin/creditCards/index.blade.php
@extends('layouts.admin')
@section('content')
@can('credit_card_create')
    <div style="margin-bottom: 10px;" class="row">
        <div class="col-lg-12">
            <a class="btn btn-success" href="{{ route('admin.credit-cards.create') }}">
                {{ trans('global.add') }} {{ trans('cruds.creditCard.title_singular') }}
            </a>
        </div>
    </div>
@endcan
<div class="card">
    <div class="card-header">
        {{ trans('cruds.creditCard.title_singular') }} {{ trans('global.list') }}
    </div>

    <div class="card-body">
        <table class=" table table-bordered table-striped table-hover ajaxTable datatable datatable-CreditCard">
            <thead>
                <tr>
                    <th width="10">

                    </th>
                    <th>
                        {{ trans('cruds.creditCard.fields.id') }}
                    </th>
                    <th>
                        {{ trans('cruds.creditCard.fields.user') }}
                    </th>
                    <th>
                        {{ trans('cruds.creditCard.fields.name') }}
                    </th>
                    <th>
                        {{ trans('cruds.creditCard.fields.token') }}
                    </th>
                    <th>
                        {{ trans('cruds.creditCard.fields.last_digits') }}
                    </th>
                    <th>
                        {{ trans('cruds.creditCard.fields.is_default') }}
                    </th>
                    <th>
                        &nbsp;
                    </th>
                </tr>
            </thead>
        </table>
    </div>
</div>



@endsection
@section('scripts')
@parent
<script>
    $(function () {
  let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
@can('credit_card_delete')
  let deleteButtonTrans = '{{ trans('global.datatables.delete') }}';
  let deleteButton = {
    text: deleteButtonTrans,
    url: "{{ route('admin.credit-cards.massDestroy') }}",
    className: 'btn-danger',
    action: function (e, dt, node, config) {
      var ids = $.map(dt.rows({ selected: true }).data(), function (entry) {
          return entry.id
      });

      if (ids.length === 0) {
        alert('{{ trans('global.datatables.zero_selected') }}')

        return
      }

      if (confirm('{{ trans('global.areYouSure') }}')) {
        $.ajax({
          headers: {'x-csrf-token': _token},
          method: 'POST',
          url: config.url,
          data: { ids: ids, _method: 'DELETE' }})
          .done(function () { location.reload() })
      }
    }
  }
  dtButtons.push(deleteButton)
@endcan

  let dtOverrideGlobals = {
    buttons: dtButtons,
    processing: true,
    serverSide: true,
    retrieve: true,
    aaSorting: [],
    ajax: "{{ route('admin.credit-cards.index') }}",
    columns: [
      { data: 'placeholder', name: 'placeholder' },
{ data: 'id', name: 'id' },
{ data: 'user_email', name: 'user.email' },
{ data: 'name', name: 'name' },
{ data: 'token', name: 'token' },
{ data: 'last_digits', name: 'last_digits' },
{ data: 'is_default', name: 'is_default' },
{ data: 'actions', name: '{{ trans('global.actions') }}' }
    ],
    orderCellsTop: true,
    order: [[ 1, 'desc' ]],
    pageLength: 100,
  };
  let table = $('.datatable-CreditCard').DataTable(dtOverrideGlobals);
  $('a[data-toggle="tab"]').on('shown.bs.tab click', function(e){
      $($.fn.dataTable.tables(true)).DataTable()
          .columns.adjust();
  });
  
});

</script>
@endsection

resources/views/admin/creditCards/show.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.show') }} {{ trans('cruds.creditCard.title') }}
    </div>

    <div class="card-body">
        <div class="form-group">
            <div class="form-group">
                <a class="btn btn-default" href="{{ route('admin.credit-cards.index') }}">
                    {{ trans('global.back_to_list') }}
                </a>
            </div>
            <table class="table table-bordered table-striped">
                <tbody>
                    <tr>
                        <th>
                            {{ trans('cruds.creditCard.fields.id') }}
                        </th>
                        <td>
                            {{ $creditCard->id }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.creditCard.fields.user') }}
                        </th>
                        <td>
                            {{ $creditCard->user->email ?? '' }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.creditCard.fields.name') }}
                        </th>
                        <td>
                            {{ $creditCard->name }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.creditCard.fields.token') }}
                        </th>
                        <td>
                            {{ $creditCard->token }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.creditCard.fields.last_digits') }}
                        </th>
                        <td>
                            {{ $creditCard->last_digits }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.creditCard.fields.is_default') }}
                        </th>
                        <td>
                            {{ App\Models\CreditCard::IS_DEFAULT_RADIO[$creditCard->is_default] ?? '' }}
                        </td>
                    </tr>
                </tbody>
            </table>
            <div class="form-group">
                <a class="btn btn-default" href="{{ route('admin.credit-cards.index') }}">
                    {{ trans('global.back_to_list') }}
                </a>
            </div>
        </div>
    </div>
</div>



@endsection